
-- alias only exists during the query
SELECT
	DISTINCT salary_currency AS unique_currency -- select unique values of a column and give it an alias
FROM
	main.data_jobs;


SELECT
	COUNT(DISTINCT salary_currency) AS number_currencies -- count number of unique occurences in a column, also giving aliasing clause AS
FROM
	main.data_jobs;
	

-- alias without AS command
-- which approach do you think is most readable?
SELECT
	COUNT(DISTINCT salary_currency) number_currencies
FROM
	main.data_jobs;

-- alias for generated by built-in function
SELECT
	ROW_NUMBER() OVER () AS id,
	*
FROM
	main.data_jobs;